[BUGFIX] Fix error with xclass using
AOEpeople/scheduler_timeline pull request #39
Opened 2016-10-25 14:18 UTC by SvenJuergens

hi, i got a 

> Fatal error: Class 'Scheduler' not found in /typo3_src-6.2.27/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4469

if an extension is installed which use `t3lib_div::makeInstance('tx_scheduler')` for example EXT:external_import in Verison 2.5.1 (last Version for 6.2)

so in TYPO3 6.2.x i can't use both extensions, with the pull request this is fixed

2016-11-01 13:14 UTC, tomasnorre requested changes
Hi,

Thanks for pointing us into this direction, as the tx_scheduler classes doesn't exist anymore this XCLASS can be completely removed. 

Therefore we would like you to update the pull-request with the line 8 removed, this will fix the issue as well. 

We would like to do is this way to credit you for the pull-request. 

Thanks in advance.

2016-11-01 15:57 UTC, SvenJuergens commented
hi,

thanks for your comment, i removed the line.

2016-11-02 07:30 UTC, tomasnorre approved these changes

2016-11-02 07:31 UTC, tomasnorre commented
@SvenJuergens 
Thanks for your fast change, i'll check why the one test is failing, and have it merged asap. 

Thanks for your contribution.

2016-11-02 10:41 UTC, SvenJuergens commented
thanks  :)

2017-05-15 13:05 UTC, closed without merging